// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package repository

import (
	"context"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (document_number)
VALUES ($1)
RETURNING id, document_number, created_at
`

// CreateAccount
//
//	INSERT INTO accounts (document_number)
//	VALUES ($1)
//	RETURNING id, document_number, created_at
func (q *Queries) CreateAccount(ctx context.Context, documentNumber string) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount, documentNumber)
	var i Account
	err := row.Scan(&i.ID, &i.DocumentNumber, &i.CreatedAt)
	return i, err
}

const getAccount = `-- name: GetAccount :one
SELECT id, document_number, created_at
FROM accounts
WHERE id = $1
`

// GetAccount
//
//	SELECT id, document_number, created_at
//	FROM accounts
//	WHERE id = $1
func (q *Queries) GetAccount(ctx context.Context, id int32) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i Account
	err := row.Scan(&i.ID, &i.DocumentNumber, &i.CreatedAt)
	return i, err
}
