// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"time"
)

type Account struct {
	ID             int32
	DocumentNumber string
	CreatedAt      time.Time
}
