// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"
)

type Querier interface {
	//CreateAccount
	//
	//  INSERT INTO accounts (document_number)
	//  VALUES ($1)
	//  RETURNING id, document_number, created_at
	CreateAccount(ctx context.Context, documentNumber string) (Account, error)
	//CreateTransaction
	//
	//  INSERT INTO transactions (account_id, operation_type, amount)
	//  VALUES ($1, $2, $3)
	//  RETURNING id, account_id, operation_type, amount, event_date
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	//GetAccount
	//
	//  SELECT id, document_number, created_at
	//  FROM accounts
	//  WHERE id = $1
	GetAccount(ctx context.Context, id int32) (Account, error)
}

var _ Querier = (*Queries)(nil)
