// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transaction.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (account_id, operation_type, amount)
VALUES ($1, $2, $3)
RETURNING id, account_id, operation_type, amount, event_date
`

type CreateTransactionParams struct {
	AccountID     int32
	OperationType int16
	Amount        pgtype.Numeric
}

// CreateTransaction
//
//	INSERT INTO transactions (account_id, operation_type, amount)
//	VALUES ($1, $2, $3)
//	RETURNING id, account_id, operation_type, amount, event_date
func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction, arg.AccountID, arg.OperationType, arg.Amount)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.OperationType,
		&i.Amount,
		&i.EventDate,
	)
	return i, err
}
